#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BLL_DAL
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="QL_TUDIEN")]
	public partial class QLTDDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertKHACHHANG(KHACHHANG instance);
    partial void UpdateKHACHHANG(KHACHHANG instance);
    partial void DeleteKHACHHANG(KHACHHANG instance);
    partial void InsertLOAITU(LOAITU instance);
    partial void UpdateLOAITU(LOAITU instance);
    partial void DeleteLOAITU(LOAITU instance);
    partial void InsertTINHTHANH(TINHTHANH instance);
    partial void UpdateTINHTHANH(TINHTHANH instance);
    partial void DeleteTINHTHANH(TINHTHANH instance);
    partial void InsertTU(TU instance);
    partial void UpdateTU(TU instance);
    partial void DeleteTU(TU instance);
    partial void InsertTuDienKhachHang(TuDienKhachHang instance);
    partial void UpdateTuDienKhachHang(TuDienKhachHang instance);
    partial void DeleteTuDienKhachHang(TuDienKhachHang instance);
    partial void InsertTUYEUTHICH(TUYEUTHICH instance);
    partial void UpdateTUYEUTHICH(TUYEUTHICH instance);
    partial void DeleteTUYEUTHICH(TUYEUTHICH instance);
    #endregion
		
		public QLTDDataContext() : 
				base(global::BLL_DAL.Properties.Settings.Default.QL_TUDIENConnectionString1, mappingSource)
		{
			OnCreated();
		}
		
		public QLTDDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLTDDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLTDDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLTDDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<KHACHHANG> KHACHHANGs
		{
			get
			{
				return this.GetTable<KHACHHANG>();
			}
		}
		
		public System.Data.Linq.Table<LOAITU> LOAITUs
		{
			get
			{
				return this.GetTable<LOAITU>();
			}
		}
		
		public System.Data.Linq.Table<TINHTHANH> TINHTHANHs
		{
			get
			{
				return this.GetTable<TINHTHANH>();
			}
		}
		
		public System.Data.Linq.Table<TU> TUs
		{
			get
			{
				return this.GetTable<TU>();
			}
		}
		
		public System.Data.Linq.Table<TuDienKhachHang> TuDienKhachHangs
		{
			get
			{
				return this.GetTable<TuDienKhachHang>();
			}
		}
		
		public System.Data.Linq.Table<TUYEUTHICH> TUYEUTHICHes
		{
			get
			{
				return this.GetTable<TUYEUTHICH>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.KHACHHANG")]
	public partial class KHACHHANG : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _TAIKHOAN;
		
		private string _MATKHAU;
		
		private string _TENNGUOIDUNG;
		
		private System.Nullable<System.DateTime> _NGAYSINH;
		
		private System.Nullable<bool> _GIOITINH;
		
		private System.Nullable<int> _DIACHI;
		
		private string _EMAIL;
		
		private string _SDT;
		
		private EntitySet<TuDienKhachHang> _TuDienKhachHangs;
		
		private EntitySet<TUYEUTHICH> _TUYEUTHICHes;
		
		private EntityRef<TINHTHANH> _TINHTHANH;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnTAIKHOANChanging(string value);
    partial void OnTAIKHOANChanged();
    partial void OnMATKHAUChanging(string value);
    partial void OnMATKHAUChanged();
    partial void OnTENNGUOIDUNGChanging(string value);
    partial void OnTENNGUOIDUNGChanged();
    partial void OnNGAYSINHChanging(System.Nullable<System.DateTime> value);
    partial void OnNGAYSINHChanged();
    partial void OnGIOITINHChanging(System.Nullable<bool> value);
    partial void OnGIOITINHChanged();
    partial void OnDIACHIChanging(System.Nullable<int> value);
    partial void OnDIACHIChanged();
    partial void OnEMAILChanging(string value);
    partial void OnEMAILChanged();
    partial void OnSDTChanging(string value);
    partial void OnSDTChanged();
    #endregion
		
		public KHACHHANG()
		{
			this._TuDienKhachHangs = new EntitySet<TuDienKhachHang>(new Action<TuDienKhachHang>(this.attach_TuDienKhachHangs), new Action<TuDienKhachHang>(this.detach_TuDienKhachHangs));
			this._TUYEUTHICHes = new EntitySet<TUYEUTHICH>(new Action<TUYEUTHICH>(this.attach_TUYEUTHICHes), new Action<TUYEUTHICH>(this.detach_TUYEUTHICHes));
			this._TINHTHANH = default(EntityRef<TINHTHANH>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TAIKHOAN", DbType="NVarChar(30) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string TAIKHOAN
		{
			get
			{
				return this._TAIKHOAN;
			}
			set
			{
				if ((this._TAIKHOAN != value))
				{
					this.OnTAIKHOANChanging(value);
					this.SendPropertyChanging();
					this._TAIKHOAN = value;
					this.SendPropertyChanged("TAIKHOAN");
					this.OnTAIKHOANChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MATKHAU", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string MATKHAU
		{
			get
			{
				return this._MATKHAU;
			}
			set
			{
				if ((this._MATKHAU != value))
				{
					this.OnMATKHAUChanging(value);
					this.SendPropertyChanging();
					this._MATKHAU = value;
					this.SendPropertyChanged("MATKHAU");
					this.OnMATKHAUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENNGUOIDUNG", DbType="NVarChar(MAX)")]
		public string TENNGUOIDUNG
		{
			get
			{
				return this._TENNGUOIDUNG;
			}
			set
			{
				if ((this._TENNGUOIDUNG != value))
				{
					this.OnTENNGUOIDUNGChanging(value);
					this.SendPropertyChanging();
					this._TENNGUOIDUNG = value;
					this.SendPropertyChanged("TENNGUOIDUNG");
					this.OnTENNGUOIDUNGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGAYSINH", DbType="Date")]
		public System.Nullable<System.DateTime> NGAYSINH
		{
			get
			{
				return this._NGAYSINH;
			}
			set
			{
				if ((this._NGAYSINH != value))
				{
					this.OnNGAYSINHChanging(value);
					this.SendPropertyChanging();
					this._NGAYSINH = value;
					this.SendPropertyChanged("NGAYSINH");
					this.OnNGAYSINHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GIOITINH", DbType="Bit")]
		public System.Nullable<bool> GIOITINH
		{
			get
			{
				return this._GIOITINH;
			}
			set
			{
				if ((this._GIOITINH != value))
				{
					this.OnGIOITINHChanging(value);
					this.SendPropertyChanging();
					this._GIOITINH = value;
					this.SendPropertyChanged("GIOITINH");
					this.OnGIOITINHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DIACHI", DbType="Int")]
		public System.Nullable<int> DIACHI
		{
			get
			{
				return this._DIACHI;
			}
			set
			{
				if ((this._DIACHI != value))
				{
					if (this._TINHTHANH.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnDIACHIChanging(value);
					this.SendPropertyChanging();
					this._DIACHI = value;
					this.SendPropertyChanged("DIACHI");
					this.OnDIACHIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMAIL", DbType="NVarChar(100)")]
		public string EMAIL
		{
			get
			{
				return this._EMAIL;
			}
			set
			{
				if ((this._EMAIL != value))
				{
					this.OnEMAILChanging(value);
					this.SendPropertyChanging();
					this._EMAIL = value;
					this.SendPropertyChanged("EMAIL");
					this.OnEMAILChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SDT", DbType="Char(10)")]
		public string SDT
		{
			get
			{
				return this._SDT;
			}
			set
			{
				if ((this._SDT != value))
				{
					this.OnSDTChanging(value);
					this.SendPropertyChanging();
					this._SDT = value;
					this.SendPropertyChanged("SDT");
					this.OnSDTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KHACHHANG_TuDienKhachHang", Storage="_TuDienKhachHangs", ThisKey="TAIKHOAN", OtherKey="TaiKhoan")]
		public EntitySet<TuDienKhachHang> TuDienKhachHangs
		{
			get
			{
				return this._TuDienKhachHangs;
			}
			set
			{
				this._TuDienKhachHangs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KHACHHANG_TUYEUTHICH", Storage="_TUYEUTHICHes", ThisKey="TAIKHOAN", OtherKey="TAIKHOAN")]
		public EntitySet<TUYEUTHICH> TUYEUTHICHes
		{
			get
			{
				return this._TUYEUTHICHes;
			}
			set
			{
				this._TUYEUTHICHes.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TINHTHANH_KHACHHANG", Storage="_TINHTHANH", ThisKey="DIACHI", OtherKey="MATINH", IsForeignKey=true)]
		public TINHTHANH TINHTHANH
		{
			get
			{
				return this._TINHTHANH.Entity;
			}
			set
			{
				TINHTHANH previousValue = this._TINHTHANH.Entity;
				if (((previousValue != value) 
							|| (this._TINHTHANH.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TINHTHANH.Entity = null;
						previousValue.KHACHHANGs.Remove(this);
					}
					this._TINHTHANH.Entity = value;
					if ((value != null))
					{
						value.KHACHHANGs.Add(this);
						this._DIACHI = value.MATINH;
					}
					else
					{
						this._DIACHI = default(Nullable<int>);
					}
					this.SendPropertyChanged("TINHTHANH");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TuDienKhachHangs(TuDienKhachHang entity)
		{
			this.SendPropertyChanging();
			entity.KHACHHANG = this;
		}
		
		private void detach_TuDienKhachHangs(TuDienKhachHang entity)
		{
			this.SendPropertyChanging();
			entity.KHACHHANG = null;
		}
		
		private void attach_TUYEUTHICHes(TUYEUTHICH entity)
		{
			this.SendPropertyChanging();
			entity.KHACHHANG = this;
		}
		
		private void detach_TUYEUTHICHes(TUYEUTHICH entity)
		{
			this.SendPropertyChanging();
			entity.KHACHHANG = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.LOAITU")]
	public partial class LOAITU : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MALOAI;
		
		private string _TENLOAI;
		
		private string _NGHIALOAITU;
		
		private EntitySet<TU> _TUs;
		
		private EntitySet<TuDienKhachHang> _TuDienKhachHangs;
		
		private EntitySet<TUYEUTHICH> _TUYEUTHICHes;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMALOAIChanging(string value);
    partial void OnMALOAIChanged();
    partial void OnTENLOAIChanging(string value);
    partial void OnTENLOAIChanged();
    partial void OnNGHIALOAITUChanging(string value);
    partial void OnNGHIALOAITUChanged();
    #endregion
		
		public LOAITU()
		{
			this._TUs = new EntitySet<TU>(new Action<TU>(this.attach_TUs), new Action<TU>(this.detach_TUs));
			this._TuDienKhachHangs = new EntitySet<TuDienKhachHang>(new Action<TuDienKhachHang>(this.attach_TuDienKhachHangs), new Action<TuDienKhachHang>(this.detach_TuDienKhachHangs));
			this._TUYEUTHICHes = new EntitySet<TUYEUTHICH>(new Action<TUYEUTHICH>(this.attach_TUYEUTHICHes), new Action<TUYEUTHICH>(this.detach_TUYEUTHICHes));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MALOAI", DbType="Char(5) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MALOAI
		{
			get
			{
				return this._MALOAI;
			}
			set
			{
				if ((this._MALOAI != value))
				{
					this.OnMALOAIChanging(value);
					this.SendPropertyChanging();
					this._MALOAI = value;
					this.SendPropertyChanged("MALOAI");
					this.OnMALOAIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENLOAI", DbType="NVarChar(50)")]
		public string TENLOAI
		{
			get
			{
				return this._TENLOAI;
			}
			set
			{
				if ((this._TENLOAI != value))
				{
					this.OnTENLOAIChanging(value);
					this.SendPropertyChanging();
					this._TENLOAI = value;
					this.SendPropertyChanged("TENLOAI");
					this.OnTENLOAIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGHIALOAITU", DbType="NVarChar(100)")]
		public string NGHIALOAITU
		{
			get
			{
				return this._NGHIALOAITU;
			}
			set
			{
				if ((this._NGHIALOAITU != value))
				{
					this.OnNGHIALOAITUChanging(value);
					this.SendPropertyChanging();
					this._NGHIALOAITU = value;
					this.SendPropertyChanged("NGHIALOAITU");
					this.OnNGHIALOAITUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LOAITU_TU", Storage="_TUs", ThisKey="MALOAI", OtherKey="MALOAI")]
		public EntitySet<TU> TUs
		{
			get
			{
				return this._TUs;
			}
			set
			{
				this._TUs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LOAITU_TuDienKhachHang", Storage="_TuDienKhachHangs", ThisKey="MALOAI", OtherKey="LoaiTu")]
		public EntitySet<TuDienKhachHang> TuDienKhachHangs
		{
			get
			{
				return this._TuDienKhachHangs;
			}
			set
			{
				this._TuDienKhachHangs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LOAITU_TUYEUTHICH", Storage="_TUYEUTHICHes", ThisKey="MALOAI", OtherKey="MALOAI")]
		public EntitySet<TUYEUTHICH> TUYEUTHICHes
		{
			get
			{
				return this._TUYEUTHICHes;
			}
			set
			{
				this._TUYEUTHICHes.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TUs(TU entity)
		{
			this.SendPropertyChanging();
			entity.LOAITU = this;
		}
		
		private void detach_TUs(TU entity)
		{
			this.SendPropertyChanging();
			entity.LOAITU = null;
		}
		
		private void attach_TuDienKhachHangs(TuDienKhachHang entity)
		{
			this.SendPropertyChanging();
			entity.LOAITU1 = this;
		}
		
		private void detach_TuDienKhachHangs(TuDienKhachHang entity)
		{
			this.SendPropertyChanging();
			entity.LOAITU1 = null;
		}
		
		private void attach_TUYEUTHICHes(TUYEUTHICH entity)
		{
			this.SendPropertyChanging();
			entity.LOAITU = this;
		}
		
		private void detach_TUYEUTHICHes(TUYEUTHICH entity)
		{
			this.SendPropertyChanging();
			entity.LOAITU = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TINHTHANH")]
	public partial class TINHTHANH : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MATINH;
		
		private string _TENTINH;
		
		private EntitySet<KHACHHANG> _KHACHHANGs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMATINHChanging(int value);
    partial void OnMATINHChanged();
    partial void OnTENTINHChanging(string value);
    partial void OnTENTINHChanged();
    #endregion
		
		public TINHTHANH()
		{
			this._KHACHHANGs = new EntitySet<KHACHHANG>(new Action<KHACHHANG>(this.attach_KHACHHANGs), new Action<KHACHHANG>(this.detach_KHACHHANGs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MATINH", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MATINH
		{
			get
			{
				return this._MATINH;
			}
			set
			{
				if ((this._MATINH != value))
				{
					this.OnMATINHChanging(value);
					this.SendPropertyChanging();
					this._MATINH = value;
					this.SendPropertyChanged("MATINH");
					this.OnMATINHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENTINH", DbType="NVarChar(MAX)")]
		public string TENTINH
		{
			get
			{
				return this._TENTINH;
			}
			set
			{
				if ((this._TENTINH != value))
				{
					this.OnTENTINHChanging(value);
					this.SendPropertyChanging();
					this._TENTINH = value;
					this.SendPropertyChanged("TENTINH");
					this.OnTENTINHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TINHTHANH_KHACHHANG", Storage="_KHACHHANGs", ThisKey="MATINH", OtherKey="DIACHI")]
		public EntitySet<KHACHHANG> KHACHHANGs
		{
			get
			{
				return this._KHACHHANGs;
			}
			set
			{
				this._KHACHHANGs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_KHACHHANGs(KHACHHANG entity)
		{
			this.SendPropertyChanging();
			entity.TINHTHANH = this;
		}
		
		private void detach_KHACHHANGs(KHACHHANG entity)
		{
			this.SendPropertyChanging();
			entity.TINHTHANH = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TU")]
	public partial class TU : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _TUVUNG;
		
		private string _MALOAI;
		
		private string _PHIENAM;
		
		private string _NGHIA;
		
		private EntitySet<TUYEUTHICH> _TUYEUTHICHes;
		
		private EntityRef<LOAITU> _LOAITU;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnTUVUNGChanging(string value);
    partial void OnTUVUNGChanged();
    partial void OnMALOAIChanging(string value);
    partial void OnMALOAIChanged();
    partial void OnPHIENAMChanging(string value);
    partial void OnPHIENAMChanged();
    partial void OnNGHIAChanging(string value);
    partial void OnNGHIAChanged();
    #endregion
		
		public TU()
		{
			this._TUYEUTHICHes = new EntitySet<TUYEUTHICH>(new Action<TUYEUTHICH>(this.attach_TUYEUTHICHes), new Action<TUYEUTHICH>(this.detach_TUYEUTHICHes));
			this._LOAITU = default(EntityRef<LOAITU>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TUVUNG", DbType="Char(30) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string TUVUNG
		{
			get
			{
				return this._TUVUNG;
			}
			set
			{
				if ((this._TUVUNG != value))
				{
					this.OnTUVUNGChanging(value);
					this.SendPropertyChanging();
					this._TUVUNG = value;
					this.SendPropertyChanged("TUVUNG");
					this.OnTUVUNGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MALOAI", DbType="Char(5) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MALOAI
		{
			get
			{
				return this._MALOAI;
			}
			set
			{
				if ((this._MALOAI != value))
				{
					if (this._LOAITU.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMALOAIChanging(value);
					this.SendPropertyChanging();
					this._MALOAI = value;
					this.SendPropertyChanged("MALOAI");
					this.OnMALOAIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PHIENAM", DbType="NVarChar(100)")]
		public string PHIENAM
		{
			get
			{
				return this._PHIENAM;
			}
			set
			{
				if ((this._PHIENAM != value))
				{
					this.OnPHIENAMChanging(value);
					this.SendPropertyChanging();
					this._PHIENAM = value;
					this.SendPropertyChanged("PHIENAM");
					this.OnPHIENAMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGHIA", DbType="NVarChar(MAX)")]
		public string NGHIA
		{
			get
			{
				return this._NGHIA;
			}
			set
			{
				if ((this._NGHIA != value))
				{
					this.OnNGHIAChanging(value);
					this.SendPropertyChanging();
					this._NGHIA = value;
					this.SendPropertyChanged("NGHIA");
					this.OnNGHIAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TU_TUYEUTHICH", Storage="_TUYEUTHICHes", ThisKey="TUVUNG,MALOAI", OtherKey="TUVUNG,MALOAI")]
		public EntitySet<TUYEUTHICH> TUYEUTHICHes
		{
			get
			{
				return this._TUYEUTHICHes;
			}
			set
			{
				this._TUYEUTHICHes.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LOAITU_TU", Storage="_LOAITU", ThisKey="MALOAI", OtherKey="MALOAI", IsForeignKey=true)]
		public LOAITU LOAITU
		{
			get
			{
				return this._LOAITU.Entity;
			}
			set
			{
				LOAITU previousValue = this._LOAITU.Entity;
				if (((previousValue != value) 
							|| (this._LOAITU.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._LOAITU.Entity = null;
						previousValue.TUs.Remove(this);
					}
					this._LOAITU.Entity = value;
					if ((value != null))
					{
						value.TUs.Add(this);
						this._MALOAI = value.MALOAI;
					}
					else
					{
						this._MALOAI = default(string);
					}
					this.SendPropertyChanged("LOAITU");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TUYEUTHICHes(TUYEUTHICH entity)
		{
			this.SendPropertyChanging();
			entity.TU = this;
		}
		
		private void detach_TUYEUTHICHes(TUYEUTHICH entity)
		{
			this.SendPropertyChanging();
			entity.TU = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TuDienKhachHang")]
	public partial class TuDienKhachHang : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Tu;
		
		private string _LoaiTu;
		
		private string _PhienAm;
		
		private string _Nghia;
		
		private string _TaiKhoan;
		
		private EntityRef<KHACHHANG> _KHACHHANG;
		
		private EntityRef<LOAITU> _LOAITU1;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnTuChanging(string value);
    partial void OnTuChanged();
    partial void OnLoaiTuChanging(string value);
    partial void OnLoaiTuChanged();
    partial void OnPhienAmChanging(string value);
    partial void OnPhienAmChanged();
    partial void OnNghiaChanging(string value);
    partial void OnNghiaChanged();
    partial void OnTaiKhoanChanging(string value);
    partial void OnTaiKhoanChanged();
    #endregion
		
		public TuDienKhachHang()
		{
			this._KHACHHANG = default(EntityRef<KHACHHANG>);
			this._LOAITU1 = default(EntityRef<LOAITU>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tu", DbType="Char(30) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Tu
		{
			get
			{
				return this._Tu;
			}
			set
			{
				if ((this._Tu != value))
				{
					this.OnTuChanging(value);
					this.SendPropertyChanging();
					this._Tu = value;
					this.SendPropertyChanged("Tu");
					this.OnTuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LoaiTu", DbType="Char(5) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string LoaiTu
		{
			get
			{
				return this._LoaiTu;
			}
			set
			{
				if ((this._LoaiTu != value))
				{
					if (this._LOAITU1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnLoaiTuChanging(value);
					this.SendPropertyChanging();
					this._LoaiTu = value;
					this.SendPropertyChanged("LoaiTu");
					this.OnLoaiTuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PhienAm", DbType="NVarChar(100)")]
		public string PhienAm
		{
			get
			{
				return this._PhienAm;
			}
			set
			{
				if ((this._PhienAm != value))
				{
					this.OnPhienAmChanging(value);
					this.SendPropertyChanging();
					this._PhienAm = value;
					this.SendPropertyChanged("PhienAm");
					this.OnPhienAmChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nghia", DbType="NVarChar(MAX)")]
		public string Nghia
		{
			get
			{
				return this._Nghia;
			}
			set
			{
				if ((this._Nghia != value))
				{
					this.OnNghiaChanging(value);
					this.SendPropertyChanging();
					this._Nghia = value;
					this.SendPropertyChanged("Nghia");
					this.OnNghiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TaiKhoan", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string TaiKhoan
		{
			get
			{
				return this._TaiKhoan;
			}
			set
			{
				if ((this._TaiKhoan != value))
				{
					if (this._KHACHHANG.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnTaiKhoanChanging(value);
					this.SendPropertyChanging();
					this._TaiKhoan = value;
					this.SendPropertyChanged("TaiKhoan");
					this.OnTaiKhoanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KHACHHANG_TuDienKhachHang", Storage="_KHACHHANG", ThisKey="TaiKhoan", OtherKey="TAIKHOAN", IsForeignKey=true)]
		public KHACHHANG KHACHHANG
		{
			get
			{
				return this._KHACHHANG.Entity;
			}
			set
			{
				KHACHHANG previousValue = this._KHACHHANG.Entity;
				if (((previousValue != value) 
							|| (this._KHACHHANG.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._KHACHHANG.Entity = null;
						previousValue.TuDienKhachHangs.Remove(this);
					}
					this._KHACHHANG.Entity = value;
					if ((value != null))
					{
						value.TuDienKhachHangs.Add(this);
						this._TaiKhoan = value.TAIKHOAN;
					}
					else
					{
						this._TaiKhoan = default(string);
					}
					this.SendPropertyChanged("KHACHHANG");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LOAITU_TuDienKhachHang", Storage="_LOAITU1", ThisKey="LoaiTu", OtherKey="MALOAI", IsForeignKey=true)]
		public LOAITU LOAITU1
		{
			get
			{
				return this._LOAITU1.Entity;
			}
			set
			{
				LOAITU previousValue = this._LOAITU1.Entity;
				if (((previousValue != value) 
							|| (this._LOAITU1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._LOAITU1.Entity = null;
						previousValue.TuDienKhachHangs.Remove(this);
					}
					this._LOAITU1.Entity = value;
					if ((value != null))
					{
						value.TuDienKhachHangs.Add(this);
						this._LoaiTu = value.MALOAI;
					}
					else
					{
						this._LoaiTu = default(string);
					}
					this.SendPropertyChanged("LOAITU1");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TUYEUTHICH")]
	public partial class TUYEUTHICH : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _TUVUNG;
		
		private string _MALOAI;
		
		private string _TAIKHOAN;
		
		private EntityRef<KHACHHANG> _KHACHHANG;
		
		private EntityRef<LOAITU> _LOAITU;
		
		private EntityRef<TU> _TU;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnTUVUNGChanging(string value);
    partial void OnTUVUNGChanged();
    partial void OnMALOAIChanging(string value);
    partial void OnMALOAIChanged();
    partial void OnTAIKHOANChanging(string value);
    partial void OnTAIKHOANChanged();
    #endregion
		
		public TUYEUTHICH()
		{
			this._KHACHHANG = default(EntityRef<KHACHHANG>);
			this._LOAITU = default(EntityRef<LOAITU>);
			this._TU = default(EntityRef<TU>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TUVUNG", DbType="Char(30) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string TUVUNG
		{
			get
			{
				return this._TUVUNG;
			}
			set
			{
				if ((this._TUVUNG != value))
				{
					if (this._TU.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnTUVUNGChanging(value);
					this.SendPropertyChanging();
					this._TUVUNG = value;
					this.SendPropertyChanged("TUVUNG");
					this.OnTUVUNGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MALOAI", DbType="Char(5) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MALOAI
		{
			get
			{
				return this._MALOAI;
			}
			set
			{
				if ((this._MALOAI != value))
				{
					if ((this._LOAITU.HasLoadedOrAssignedValue || this._TU.HasLoadedOrAssignedValue))
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMALOAIChanging(value);
					this.SendPropertyChanging();
					this._MALOAI = value;
					this.SendPropertyChanged("MALOAI");
					this.OnMALOAIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TAIKHOAN", DbType="NVarChar(30) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string TAIKHOAN
		{
			get
			{
				return this._TAIKHOAN;
			}
			set
			{
				if ((this._TAIKHOAN != value))
				{
					if (this._KHACHHANG.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnTAIKHOANChanging(value);
					this.SendPropertyChanging();
					this._TAIKHOAN = value;
					this.SendPropertyChanged("TAIKHOAN");
					this.OnTAIKHOANChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KHACHHANG_TUYEUTHICH", Storage="_KHACHHANG", ThisKey="TAIKHOAN", OtherKey="TAIKHOAN", IsForeignKey=true)]
		public KHACHHANG KHACHHANG
		{
			get
			{
				return this._KHACHHANG.Entity;
			}
			set
			{
				KHACHHANG previousValue = this._KHACHHANG.Entity;
				if (((previousValue != value) 
							|| (this._KHACHHANG.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._KHACHHANG.Entity = null;
						previousValue.TUYEUTHICHes.Remove(this);
					}
					this._KHACHHANG.Entity = value;
					if ((value != null))
					{
						value.TUYEUTHICHes.Add(this);
						this._TAIKHOAN = value.TAIKHOAN;
					}
					else
					{
						this._TAIKHOAN = default(string);
					}
					this.SendPropertyChanged("KHACHHANG");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LOAITU_TUYEUTHICH", Storage="_LOAITU", ThisKey="MALOAI", OtherKey="MALOAI", IsForeignKey=true)]
		public LOAITU LOAITU
		{
			get
			{
				return this._LOAITU.Entity;
			}
			set
			{
				LOAITU previousValue = this._LOAITU.Entity;
				if (((previousValue != value) 
							|| (this._LOAITU.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._LOAITU.Entity = null;
						previousValue.TUYEUTHICHes.Remove(this);
					}
					this._LOAITU.Entity = value;
					if ((value != null))
					{
						value.TUYEUTHICHes.Add(this);
						this._MALOAI = value.MALOAI;
					}
					else
					{
						this._MALOAI = default(string);
					}
					this.SendPropertyChanged("LOAITU");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TU_TUYEUTHICH", Storage="_TU", ThisKey="TUVUNG,MALOAI", OtherKey="TUVUNG,MALOAI", IsForeignKey=true)]
		public TU TU
		{
			get
			{
				return this._TU.Entity;
			}
			set
			{
				TU previousValue = this._TU.Entity;
				if (((previousValue != value) 
							|| (this._TU.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TU.Entity = null;
						previousValue.TUYEUTHICHes.Remove(this);
					}
					this._TU.Entity = value;
					if ((value != null))
					{
						value.TUYEUTHICHes.Add(this);
						this._TUVUNG = value.TUVUNG;
						this._MALOAI = value.MALOAI;
					}
					else
					{
						this._TUVUNG = default(string);
						this._MALOAI = default(string);
					}
					this.SendPropertyChanged("TU");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
